name: Build and Test streaming UT

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master_
      - development_

jobs:
  build:
    runs-on: [macos-14]

    steps:
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4.0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build iOS and Test Streaming UT
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          action: build test
          build-settings: ONLY_ACTIVE_ARCH=NO TEST_AFTER_BUILD=YES
          configuration: Debug
          derived-data-path: "${{github.workspace}}/SplitApp"
          destination: 'platform=iOS Simulator,OS=17.2,name=iPhone 15'
          project: Split.xcodeproj
          scheme: Split
          sdk: 'iphonesimulator'
          test-plan: 'SplitStreamingUT'
          use-xcpretty: true

      # - name: Install java 11
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'oracle'
      #     java-version: '17'

      # - name: SonarQube Install
      #   uses: mathrix-education/sonar-scanner@master
      #   env:
      #     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      #   with:
      #     version: 4.8.0.2856
      #     scan: false

      # - name: SonarQube Scan
      #   run: >
      #     sonar-scanner --debug
      #     -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
      #     -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} 
      #     -Dsonar.projectName=${{ github.event.repository.name }} 
      #     -Dsonar.projectKey=splitio_ios-client 
      #     -Dsonar.github.token=${{ secrets.GITHUB_TOKEN }} 
      #     -Dsonar.c.file.suffixes=- 
      #     -Dsonar.cpp.file.suffixes=- 
      #     -Dsonar.objc.file.suffixes=-
