name: Build and Test iOS Streaming

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: [macos-14]

    steps:
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4.0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test iOS Streaming integration
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          action: build test
          build-settings: ONLY_ACTIVE_ARCH=NO TEST_AFTER_BUILD=YES
          configuration: Debug
          derived-data-path: "${{github.workspace}}/SplitApp"
          destination: 'platform=iOS Simulator,OS=17.2,name=iPhone 15'
          project: Split.xcodeproj
          scheme: Split
          sdk: 'iphonesimulator'
          test-plan: 'SplitiOSStreaming'
          use-xcpretty: true
